name: Package ID

on:
    workflow_dispatch:
        
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Get PackageId from .csproj
        id: get-package-id
        run: |
          PROJECT_FILE=$(find . -name "*.csproj" | head -n 1)
          PACKAGE_ID=$(xmllint --xpath "string(//PackageId)" "$PROJECT_FILE")
          if [ -z "$PACKAGE_ID" ]; then
            # fallback to AssemblyName if PackageId isn't defined
            PACKAGE_ID=$(xmllint --xpath "string(//AssemblyName)" "$PROJECT_FILE")
          fi
          echo "PackageId: $PACKAGE_ID"
          echo "package_id=$PACKAGE_ID" >> $GITHUB_OUTPUT
