name: Publish .NET Package

on:
  workflow_dispatch:
    inputs:
      package_version:
        description: 'Package version (e.g., 1.0.3)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack with version ${{ inputs.package_version }}
        run: dotnet pack --configuration Release --no-build --output ./nupkg /p:PackageVersion=${{ inputs.package_version }}

      - name: Add GitHub Packages source
        run: dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --name "github" --username "${{ github.actor }}" --password "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text

      - name: Publish to GitHub Packages
        run: dotnet nuget push "./nupkg/*.nupkg" --source "github" --api-key "${{ secrets.GITHUB_TOKEN }}" --skip-duplicate
