
name: Publish .NET Package

on:
  workflow_dispatch:
    inputs:
      package_version:
        description: 'Package version (e.g., 1.0.3)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore skip_remover.csproj

      - name: Build
        run: dotnet build skip_remover.csproj --configuration Release --no-restore

      - name: Create .exe ${{ inputs.package_version }}
        run: |
          dotnet publish skip_remover.csproj --configuration Release --runtime win-x64 --self-contained true -p:PublishSingleFile=true
          dotnet publish skip_remover.csproj --configuration Release --runtime linux-x64 --self-contained true -p:PublishSingleFile=true

          ls -R
          mv ./bin/Release/net8.0/win-x64/publish/skip_remover.exe ./bin/Release/net8.0/win-x64/publish/skip_remover_win-x64.exe 
          mv ./bin/Release/net8.0/linux-x64/publish/skip_remover ./bin/Release/net8.0/linux-x64/publish/skip_remover_linux-x64.exe

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ inputs.package_version }}
          name: Release v${{ inputs.package_version }}
          files: |
            bin/Release/net8.0/win-x64/publish/*.exe
            bin/Release/net8.0/linux-x64/publish/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}